### ISSUE TITLE
trash and rm options

### ISSUE THREAD

**Issue by grylem** [BlackHole1/trash#1]
Hi.
mkdir test
touch test/test

rm test
rm: test: is a directory

trash test
moves to without warning

trash -i test
same

can you make the trash accept all rm options and warning?
Thanks.

**Comment by BlackHole1** [comment]
Hi @grylem thank you for your feedback. This is theoretically possible, but at the moment I may not have much time to do it. And this project does not completely imitate the rm command, the best way I can think of is to rewrite a project.

**Comment by grylem** [comment]
**@BlackHole1**

maybe someday you will have time...
